# Generated by Django 4.0 on 2022-01-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
    ]
